---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./external-dns.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
