---
collections:
  - name: community.general
    version: 12.4.0
  - name: vladgh.samba
    version: 3.5.4
roles:
  - name: robertdebock.storage
    src: https://github.com/robertdebock/ansible-role-storage
    version: 6.0.4
  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker
    version: 8.0.0
  - name: geerlingguy.security
    src: https://github.com/geerlingguy/ansible-role-security
    version: 3.0.0
