#ENC[AES256_GCM,data:rU84YfGpnQQ=,iv:JVSotPsI9UBOMgQHZqSfFrLBOd1JRz6QlQQRsGnOfUU=,tag:qCOWSFu8GyYgwrwGNmldVw==,type:comment]
generic__database_encryption_passphrase: ENC[AES256_GCM,data:KgkKdIw1lDNVJazkfoWBsFQLoAXLYK0KVjp6E0DD+l8dAr15xJbduoOrqAsVpSW7ocJq53CxYqoLEBqZQOb+kA==,iv:R6MLANS9UmOLk4II4k172WFqOOvR0DQ6ov1+RPdj4lw=,tag:3W3MXA5N7k/UpWJR+q9/8A==,type:str]
generic__database_backup_storage_account_name: ENC[AES256_GCM,data:E2HAYHsGUhYeu94KOA4Yas9y9g==,iv:uVut8CWrtyXOiBkZXg+x1OLFoA4pAyDVCDqs3NvpqZA=,tag:eAmBQig8Unmhw7W+psOeUg==,type:str]
generic__database_backup_storage_account_key: ENC[AES256_GCM,data:O3D9gCS8vTr7qCu//6CMaQtHkH1sK9ym6wqF44icGjLxYW/+D1Z84VpDSd5pBeryd4t72z/Hx604k5QZAvYb41pUkg0Kh6tiYOKdqs5+GKky3YgINZkjvQ==,iv:9W1pOS0MyCiphaixRrz4PkOaS8w++VBcL+bHURvoNGw=,tag:buaBTZWnMJ8MgHedOKhjsQ==,type:str]
#ENC[AES256_GCM,data:xH1mZmGOtekL0pddt4k=,iv:OkxMaN8fg18FcJ5x4yslfVwfkmE37G8xKf19I6NJdoc=,tag:4/GqGSybsUE1xViIi+gOdA==,type:comment]
notifications__mailrise_smtp_password: ENC[AES256_GCM,data:WUSMm9Tyq2WHOnUkHWIW7y6gKX5KYuxe16v9KReLHRd63+RHDrSpsnSSq/kP3PR6l+X/zdG8GPW9JCnG5aFD8w==,iv:7Vmtkm+u9AA4Bv7+ddPLtRFyqpJSuZ120jrjjjurz5o=,tag:0k87LvtqQHXx9ZMgY0eUTQ==,type:str]
#ENC[AES256_GCM,data:bvF/JgA=,iv:6ohFEwjJlQz9gG8+WubBFTVdvlGrdfUkOrAIBsITIqQ=,tag:Z8ZseSFvJfr6NDNrdbbw9w==,type:comment]
#ENC[AES256_GCM,data:6XiAMbpyMof+IKL9Czw=,iv:5LG06/fFIamiALFDLFlFQqlq32t0tZXoOxGoay/Mr2Y=,tag:pivCeqfQqzNY6ICFEuvWzQ==,type:comment]
apps__oauth2_proxy_azure_client_id: ENC[AES256_GCM,data:AmyaO+miasx41+qCUTgIFLv5uVl4NOSoBSmwNpyJHXEnT7p0,iv:w3+p4rebaiIHLpGDrURr8X5qU+kXbwJ8uUXxJECU7nw=,tag:D+ZctteVZ5DEUfJexy3CEQ==,type:str]
apps__oauth2_proxy_azure_client_secret: ENC[AES256_GCM,data:FUfwsGQY0T/I6GxYTyh6GjkgMnbsIAgf1AkRkuaoFkpwK/SKWBzeQg==,iv:kuyjutQkm2/5y0swVKsDx9WN2IS+QBf2p6qRvlj2GlQ=,tag:Miq05QxQjTFmo2PU5F5S2w==,type:str]
#ENC[AES256_GCM,data:6SYMncMo1qoM0Q==,iv:duT8JV4AlE05wAzb4Kp28A7m1NrhliQixf9Y6BpcbKI=,tag:/Z3N+lhpeo1zaBYHqt8mtA==,type:comment]
apps__influxdb_password: ENC[AES256_GCM,data:6iJthMgPdtBDdthBGKFI6Sz8J1KdAIO4zQ2QGnfMEc3tZdDC1e4VVO7ES3ZeR6RQTWBNRJ5T/euZmVuGvURzQA==,iv:a6f9ehH0lnBBgpfULx447Psqadte2zm0aj5KxfWVrfY=,tag:78/rk6DA+IL63pCvI2mfeQ==,type:str]
apps__influxdb_admin_token: ENC[AES256_GCM,data:T7KfY2UegS74EF8p3T3PKB0qpQSvI9DKweH6dTL+7zI2744hl+8oMIFGsWc5CAyzTiy+mVQSJTofY0NJ07qmiw==,iv:a6coiafzKS+AAju27ak5GC8KNapgB+CEatQ7fyyDQzo=,tag:Uaxy1AyCkW8HD0uiqEuv5w==,type:str]
#ENC[AES256_GCM,data:E36VcHT1DRf3boifOeYmBaMx1pDtSg==,iv:y5j+81z6V075CSJgcfxu7IVhHLRkmzFJ21U9/uoNxoA=,tag:0KjKKifNFuVGQp/QMTYW4A==,type:comment]
apps__traefik_forward_auth_secret: ENC[AES256_GCM,data:0QRdsFcJvMhvgc3VWGom2hjAn2r5T1Ji+gm7R/FGjJjwxvZ6YMDQwHBu+HhOKhljsCoUBNOAhTKM2cwgWVXmug==,iv:CqVa5uAN4nfisHzHtJFwQTN9N3V3ScpOMq1FjcbXLXw=,tag:zShWCVozD7tvUZDDk1hH8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182vhhzupcql0c9l272gm3z004x7hnukt7ptugwqwrqnh2slyu9zskphzdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT1RYWUFvZE9UQkcwb1Nx
            M2U4WUxwdi9JVVJlUzZFWWlkOXY5ejM0MUhNClJ0NUhQYjlWb3VIYmgra0dUWnhW
            ZU5JdVdYSzBXSExmbjN6cEZJMUtOYUkKLS0tIDdGTi9md1F2WHRtMVpXMUhSK2hI
            eVBKRXVRTE0xSGdTQzF6enJtNnMzOGcKfIhR/2B8E7FhoP5b+fRdpPwIwE7gOrIa
            mR6EnBhQi6Cr/LM/7nwWvCt/E/2IoDLMPPl7f1xyDPIjV/fY5XncqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T14:23:41Z"
    mac: ENC[AES256_GCM,data:W+2DRysxMWU69/283KM97k6S+LhTUzh0dIyx9ooKtekMpgurfwajZJWVtZi0WAgmPrkQhsaM4C3lndm/eqqFfGFx0+Syw3tqlVXek64m7lFdYbUy4bTRM8GBpxGpTqqP73GEC4BTK9kMDAjrLidizMMCLxyebLg36mXSYBIFKgs=,iv:BYxuvk9Nm8GvoEemEOfST97ExLhdV4UQ0v2iqEt+PPw=,tag:rp/9CX8QGMHFCwyLNzNFdA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
