services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:version-v1.5.3@sha256:001875e61839c8a50743f0bc0fa4da2a55ed8a038b9b5ed0dd2c663dd3d0bfc7
    container_name: bazarr
    depends_on:
      - traefik
    restart: always
    security_opt:
      - no-new-privileges=true
    # Started with 2048m to test
    mem_limit: 2048m
    volumes:
      - bazarr_config_data:/config
      - /mnt/smb_share_movies:/movies
      - /mnt/smb_share_tv:/tv
    # Linuxserver uses s6 overlay which requires root permissions to set correct /run permissions
    # Root permissions will be dropped after initialization
    # user: "$PUID:$PGID"
    healthcheck:
      test: curl -f http://localhost:6767/ping || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - bazarr-frontend
      - arr-stack-backend
    labels:
      # Homepage
      - homepage.group=Media
      - homepage.name=Bazarr
      - homepage.icon=bazarr
      - homepage.href=https://bazarr.$DOMAINNAME
      - homepage.description=Subtitle Manager
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=bazarr-frontend"
      ## Middlewares
      - "traefik.http.routers.bazarr-rtr.middlewares=chain-auth@file"
      ## HTTP Services
      - "traefik.http.routers.bazarr-rtr.service=bazarr"
      # Enable the management port
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      ## Router for Gatus â€” bypass auth if secret header is present
      - "traefik.http.routers.bazarr-monitor-rtr.rule=Host(`bazarr.$DOMAINNAME`) && Header(`X-Monitor-Key`, `$GENERIC_MONITORING_HEADER_SECRET`)"
      - "traefik.http.routers.bazarr-monitor-rtr.service=bazarr"
      - "traefik.http.routers.bazarr-monitor-rtr.priority=100"  # Higher priority so it matches first

volumes:
  bazarr_config_data:

networks:
  bazarr-frontend:
    name: bazarr-frontend
