services:
  dawarich-redis:
    image: redis:8.4.0-alpine@sha256:6cbef353e480a8a6e7f10ec545f13d7d3fa85a212cdcc5ffaf5a1c818b9d3798
    container_name: dawarich-redis
    command: redis-server
    networks:
      - dawarich-backend
    volumes:
      - dawarich_shared:/data
    restart: always
    mem_limit: 1024m
    security_opt:
      - no-new-privileges=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich-db:
    image: postgis/postgis:17-3.5-alpine@sha256:f7f09b5a1b253149e3031c3eb52eb784ae7646bc176f5a985308cfd475465232
    shm_size: 1G
    container_name: dawarich-db
    volumes:
      - dawarich_db_data:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf # Optional, uncomment if you want to use a custom config
    networks:
      - dawarich-backend
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - POSTGRES_USER=dawarich
      - POSTGRES_PASSWORD=${DAWARICH_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-dawarich_development}
    restart: always
    mem_limit: 1024m
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-dawarich_development}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use custom config, uncomment if you want to use a custom config

  dawarich-db-backup:
    container_name: dawarich-db-backup
    image: tiredofit/db-backup:4.1.21@sha256:36e7888e4887e57e3ab3ec5ecd4782f345226084df6d3fdd93b2d3e4a2162274
    depends_on:
      - dawarich-db
    volumes:
      - /mnt/smb_share_backup/dawarich:/backup
    mem_limit: 1024m
    networks:
      - dawarich-backend
    environment:
      - TIMEZONE=${TZ}
      - USER_DBBACKUP=${PUID}
      - GROUP_DBBACKUP=${PGID}
      - CONTAINER_NAME=dawarich-db-backup
      - CONTAINER_ENABLE_MONITORING=FALSE # Disables Zabbix backup statistics

      - ENABLE_NOTIFICATIONS=TRUE
      - NOTIFICATION_TYPE=EMAIL
      - SMTP_HOST=${NOTIFICATIONS_EMAIL_HOST}
      - SMTP_DOMAIN=${NOTIFICATIONS_EMAIL_DOMAIN}
      - SMTP_PORT=${NOTIFICATIONS_EMAIL_PORT}
      - SMTP_USER=${NOTIFICATIONS_EMAIL_USERNAME}
      - SMTP_PASS=${NOTIFICATIONS_EMAIL_PASSWORD}
      - MAIL_TO=${NOTIFICATIONS_EMAIL_TO}
      - MAIL_FROM=${NOTIFICATIONS_EMAIL_FROM}
      - SMTP_AUTHENTICATION="on"
      - SMTP_TLSCERTCHECK=TRUE
      - SMTP_STARTTLS=on
      - SMTP_TLS=on

      - DEFAULT_CHECKSUM=SHA1        # Set standard checksum to SHA1
      - DEFAULT_COMPRESSION=ZSTD     # Compress all with ZSTD
      - DEFAULT_BACKUP_INTERVAL=1440 # Backup every 1440 minutes = 24 hours
      - DEFAULT_BACKUP_BEGIN=0000    # Start backing up at midnight
      - DEFAULT_CLEANUP_TIME=2880    # Cleanup backups after two days

      - DEFAULT_ENCRYPT=TRUE                            # Encrypt backup files with GPG
      - DEFAULT_ENCRYPT_PASSPHRASE=${DB_ENC_PASSPHRASE} # Set encryption password

      - DB01_TYPE=pgsql
      - DB01_HOST=dawarich-db
      - DB01_NAME=${POSTGRES_DB:-dawarich_development}
      - DB01_USER=dawarich
      - DB01_PORT=5432
      - DB01_PASS=${DAWARICH_DB_PASSWORD}
    restart: always
    security_opt:
      - no-new-privileges=true

  dawarich:
    image: freikin/dawarich:0.37.3@sha256:efab2e677baf912f5cc68363ec26e648015fa2c703b4a0cf8e03418415e1ed0d
    container_name: dawarich
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
      - dawarich_db_data:/dawarich_db_data
    mem_limit: ${APP_MEMORY_LIMIT:-4G}
    cpus: ${APP_CPU_LIMIT:-0.50}
    networks:
      - dawarich-frontend
      - dawarich-backend
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    security_opt:
      - no-new-privileges=true
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=${REDIS_URL:-redis://dawarich-redis:6379}
      - DATABASE_HOST=${DATABASE_HOST:-dawarich-db}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-dawarich}
      - DATABASE_PASSWORD=${DAWARICH_DB_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME:-dawarich_development}
      - MIN_MINUTES_SPENT_IN_CITY=${MIN_MINUTES_SPENT_IN_CITY:-60}
      - APPLICATION_HOSTS=${APPLICATION_HOSTS:-localhost,::1,127.0.0.1,dawarich.$DOMAINNAME,dawarich-noauth.$DOMAINNAME}
      - TIME_ZONE=${TZ:-Europe/London}
      - APPLICATION_PROTOCOL=${APPLICATION_PROTOCOL:-http}
      - PROMETHEUS_EXPORTER_ENABLED=${PROMETHEUS_EXPORTER_ENABLED:-false}
      - PROMETHEUS_EXPORTER_HOST=${PROMETHEUS_EXPORTER_HOST:-0.0.0.0}
      - PROMETHEUS_EXPORTER_PORT=${PROMETHEUS_EXPORTER_PORT:-9394}
      - SECRET_KEY_BASE=${DAWARICH_SECRET_KEY_BASE}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT:-true}
      - SELF_HOSTED=${SELF_HOSTED:-true}
      - STORE_GEODATA=${STORE_GEODATA:-true}
    labels:
      # Homepage
      - homepage.group=Productivity
      - homepage.name=Dawarich
      - homepage.icon=dawarich.svg
      - homepage.href=https://dawarich.$DOMAINNAME
      - homepage.description=Location Tracking
      # Group
      - org.label-schema.group=productivity
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=dawarich-frontend"
      ## Middlewares
      - "traefik.http.routers.dawarich-rtr.middlewares=chain-auth@file"
      ## HTTP Services
      - "traefik.http.routers.dawarich-rtr.service=dawarich"
      ### Enable the server port
      - "traefik.http.services.dawarich.loadbalancer.server.port=3000"
      ## Extra web no-auth endpoint for external access (e.g. mobile app)
      - "traefik.http.routers.dawarich-noauth-rtr.middlewares=chain-no-auth-custom-port@file"
      - "traefik.http.routers.dawarich-noauth-rtr.rule=Host(`dawarich-noauth.$DOMAINNAME`)"
      - "traefik.http.routers.dawarich-noauth-rtr.service=dawarich"
      - "traefik.http.routers.dawarich-noauth-rtr.entrypoints=https-public"
      ## Router for Gatus â€” bypass auth if secret header is present
      - "traefik.http.routers.dawarich-monitor-rtr.rule=Host(`dawarich.$DOMAINNAME`) && Header(`X-Monitor-Key`, `$GENERIC_MONITORING_HEADER_SECRET`)"
      - "traefik.http.routers.dawarich-monitor-rtr.service=dawarich"
      - "traefik.http.routers.dawarich-monitor-rtr.priority=100"  # Higher priority so it matches first
    logging:
      driver: "json-file"
      options:
        max-size: ${LOG_MAX_SIZE:-100m}
        max-file: ${LOG_MAX_FILE:-5}
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich-db:
        condition: service_healthy
        restart: true
      dawarich-redis:
        condition: service_healthy
        restart: true

  dawarich-sidekiq:
    image: freikin/dawarich:0.37.3@sha256:efab2e677baf912f5cc68363ec26e648015fa2c703b4a0cf8e03418415e1ed0d
    container_name: dawarich-sidekiq
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
    mem_limit: 2048m
    networks:
      - dawarich-backend
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    security_opt:
      - no-new-privileges=true
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=${REDIS_URL:-redis://dawarich-redis:6379}
      - DATABASE_HOST=${DATABASE_HOST:-dawarich-db}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-dawarich}
      - DATABASE_PASSWORD=${DAWARICH_DB_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME:-dawarich_development}
      - APPLICATION_HOSTS=${APPLICATION_HOSTS:-localhost,::1,127.0.0.1,dawarich-noauth.$DOMAINNAME,dawarich.$DOMAINNAME}
      - BACKGROUND_PROCESSING_CONCURRENCY=${BACKGROUND_PROCESSING_CONCURRENCY:-10}
      - APPLICATION_PROTOCOL=${APPLICATION_PROTOCOL:-http}
      - PROMETHEUS_EXPORTER_ENABLED=${PROMETHEUS_EXPORTER_ENABLED:-false}
      - PROMETHEUS_EXPORTER_HOST=${PROMETHEUS_EXPORTER_HOST_SIDEKIQ:-dawarich}
      - PROMETHEUS_EXPORTER_PORT=${PROMETHEUS_EXPORTER_PORT:-9394}
      - SECRET_KEY_BASE=${DAWARICH_SECRET_KEY_BASE}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT:-true}
      - SELF_HOSTED=${SELF_HOSTED:-true}
      - STORE_GEODATA=${STORE_GEODATA:-true}
      - TIME_ZONE=${TZ:-Europe/London}
    logging:
      driver: "json-file"
      options:
        max-size: ${LOG_MAX_SIZE:-100m}
        max-file: ${LOG_MAX_FILE:-5}
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f sidekiq" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich-db:
        condition: service_healthy
        restart: true
      dawarich-redis:
        condition: service_healthy
        restart: true
      dawarich:
        condition: service_healthy
        restart: true

volumes:
  dawarich_db_data:
  dawarich_shared:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:

networks:
  dawarich-frontend:
    name: dawarich-frontend
  dawarich-backend:
    name: dawarich-backend
