services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:version-3.1.0.4875@sha256:ede2bb17350cc97a0d3f24389aa91803f655eac29aa022c77a71f4a61cc621e4
    container_name: lidarr
    depends_on:
      - traefik
    restart: always
    security_opt:
      - no-new-privileges=true
    # Started with 2048m to test
    mem_limit: 2048m
    volumes:
      - lidarr_config_data:/config
      - /mnt/smb_share_downloads-staging/sabnzbd:/downloads
      - /mnt/smb_share_downloads-staging/torrents:/torrents
      - /mnt/smb_share_music:/music
    # Linuxserver uses s6 overlay which requires root permissions to set correct /run permissions
    # Root permissions will be dropped after initialization
    # user: "$PUID:$PGID"
    healthcheck:
      test: curl -f http://localhost:8686/ping || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - lidarr-frontend
      - arr-stack-backend
    labels:
      # Homepage
      - homepage.group=Media
      - homepage.name=Lidarr
      - homepage.icon=lidarr
      - homepage.href=https://lidarr.$DOMAINNAME
      - homepage.description=Music Collection Manager
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=lidarr-frontend"
      ## Middlewares
      - "traefik.http.routers.lidarr-rtr.middlewares=chain-auth@file"
      ## HTTP Services
      - "traefik.http.routers.lidarr-rtr.service=lidarr"
      # Enable the management port
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
      ## Router for Gatus â€” bypass auth if secret header is present
      - "traefik.http.routers.lidarr-monitor-rtr.rule=Host(`lidarr.$DOMAINNAME`) && Header(`X-Monitor-Key`, `$GENERIC_MONITORING_HEADER_SECRET`)"
      - "traefik.http.routers.lidarr-monitor-rtr.service=lidarr"
      - "traefik.http.routers.lidarr-monitor-rtr.priority=100"  # Higher priority so it matches first

volumes:
  lidarr_config_data:

networks:
  lidarr-frontend:
    name: lidarr-frontend
