services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:version-2.3.0.5236@sha256:e74a1e093dcc223d671d4b7061e2b4946f1989a4d3059654ff4e623b731c9134
    container_name: prowlarr
    depends_on:
      - traefik
    restart: always
    security_opt:
      - no-new-privileges=true
    # Started with 2048m to test
    mem_limit: 2048m
    volumes:
      - prowlarr_config_data:/config
    # Linuxserver uses s6 overlay which requires root permissions to set correct /run permissions
    # Root permissions will be dropped after initialization
    # user: "$PUID:$PGID"
    healthcheck:
      test: curl -f http://localhost:9696/ping || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - prowlarr-frontend
      - arr-stack-backend
    labels:
      # Homepage
      - homepage.group=Media
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr
      - homepage.href=https://prowlarr.$DOMAINNAME
      - homepage.description=Indexer Manager
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=prowlarr-frontend"
      ## Middlewares
      - "traefik.http.routers.prowlarr-rtr.middlewares=chain-auth@file"
      ## HTTP Services
      - "traefik.http.routers.prowlarr-rtr.service=prowlarr"
      # Enable the management port
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      ## Router for Gatus â€” bypass auth if secret header is present
      - "traefik.http.routers.prowlarr-monitor-rtr.rule=Host(`prowlarr.$DOMAINNAME`) && Header(`X-Monitor-Key`, `$GENERIC_MONITORING_HEADER_SECRET`)"
      - "traefik.http.routers.prowlarr-monitor-rtr.service=prowlarr"
      - "traefik.http.routers.prowlarr-monitor-rtr.priority=100"  # Higher priority so it matches first

volumes:
  prowlarr_config_data:

networks:
  prowlarr-frontend:
    name: prowlarr-frontend
