services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.4@sha256:c4e1276d9eec06f2520b4cdffcff49aea4215e5ac2d51bf0de81cce9f8aa85d4
    container_name: qbittorrent
    depends_on:
      - traefik
    restart: always
    security_opt:
      - no-new-privileges=true
    # Started with 1024m to test
    mem_limit: 1024m
    volumes:
      - qbittorrent_config_data:/config
      - /mnt/smb_share_downloads-staging/torrents:/torrents
      - qbittorrent_incomplete_downloads_data:/incomplete-downloads
    # Linuxserver uses s6 overlay which requires root permissions to set correct /run permissions
    # Root permissions will be dropped after initialization
    # user: "$PUID:$PGID"
    healthcheck:
      test: curl -f http://localhost:8080 || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    networks:
      - qbittorrent-frontend
      - arr-stack-backend
    labels:
      # Homepage
      - homepage.group=Media
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent
      - homepage.href=https://qbittorrent.$DOMAINNAME
      - homepage.description=Torrent Manager
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=qbittorrent-frontend"
      ## Middlewares
      - "traefik.http.routers.qbittorrent-rtr.middlewares=chain-auth@file"
      ## HTTP Services
      - "traefik.http.routers.qbittorrent-rtr.service=qbittorrent"
      # Enable the management port
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      ## Router for Gatus â€” bypass auth if secret header is present
      - "traefik.http.routers.qbittorrent-monitor-rtr.rule=Host(`qbittorrent.$DOMAINNAME`) && Header(`X-Monitor-Key`, `$GENERIC_MONITORING_HEADER_SECRET`)"
      - "traefik.http.routers.qbittorrent-monitor-rtr.service=qbittorrent"
      - "traefik.http.routers.qbittorrent-monitor-rtr.priority=100"  # Higher priority so it matches first

volumes:
  qbittorrent_config_data:
  qbittorrent_incomplete_downloads_data:

networks:
  qbittorrent-frontend:
    name: qbittorrent-frontend
