services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:version-4.0.16.2944@sha256:6f73bbba33391a338e20d836a60c86beaf2a865a89b706b339fc8cb0b8ce1559
    container_name: sonarr
    depends_on:
      - traefik
    restart: always
    security_opt:
      - no-new-privileges=true
    # Started with 2048m to test
    mem_limit: 2048m
    volumes:
      - sonarr_config_data:/config
      - /mnt/smb_share_downloads-staging/sabnzbd:/downloads
      - /mnt/smb_share_downloads-staging/torrents:/torrents
      - /mnt/smb_share_tv:/tv
    # Linuxserver uses s6 overlay which requires root permissions to set correct /run permissions
    # Root permissions will be dropped after initialization
    # user: "$PUID:$PGID"
    healthcheck:
      test: curl -f http://localhost:8989/ping || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - sonarr-frontend
      - arr-stack-backend
    labels:
      # Homepage
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr
      - homepage.href=https://sonarr.$DOMAINNAME
      - homepage.description=Personal Video Recorder
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=sonarr-frontend"
      ## Middlewares
      - "traefik.http.routers.sonarr-rtr.middlewares=chain-auth@file"
      ## HTTP Services
      - "traefik.http.routers.sonarr-rtr.service=sonarr"
      # Enable the management port
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      ## Router for Gatus â€” bypass auth if secret header is present
      - "traefik.http.routers.sonarr-monitor-rtr.rule=Host(`sonarr.$DOMAINNAME`) && Header(`X-Monitor-Key`, `$GENERIC_MONITORING_HEADER_SECRET`)"
      - "traefik.http.routers.sonarr-monitor-rtr.service=sonarr"
      - "traefik.http.routers.sonarr-monitor-rtr.priority=100"  # Higher priority so it matches first

volumes:
  sonarr_config_data:

networks:
  sonarr-frontend:
    name: sonarr-frontend
