apiVersion: v1
kind: Secret
metadata:
    name: immich
stringData:
    #ENC[AES256_GCM,data:gqIdCQ==,iv:ptfpPwNMxfxj8nTokaDUUYj11FdlqYIkHCLgZ2L8+hQ=,tag:xsuVD3skoOX+ypE9nVQMuw==,type:comment]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:DzoJwY1I,iv:Xs88bjzj5NwU7By4cTVYIKqFPM8qn9Qk2YQyTEO08Ww=,tag:v80izl5iEKoTw8uuDScruw==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:5/UcSV0gy9HcqMCL7A5QNHo6ukRR0oEhgSUAsYRI+sLcGin888o=,iv:IA6TRQUQIRglW+OcUIqf8v5CHEimXRlTJsVHZ3j7pbw=,tag:PWoINoXwCGN8HIV7cfog+A==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:9JcocmoV,iv:21GpNCSpkOBoDXWQxsa2N10pvEMcA3NY6TzWQeAmS4w=,tag:RK1gjPN6+6JuHoMYT7+JtA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ktXHKxsyHe9CBKnVvLQGN5EU1SJJnWDVnk+bUQ0RTgPzGvcYO4yC0aSgZ3dNayi2hhZ9MYO4yDto2aGnzFDcMg==,iv:GMqEoyMqRp0vxnSpzsVslC4EmgbBXehZBmrbLvuUjcg=,tag:R/9Ll3vzc9RL2c4dI0z1yw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:L6UD+MT9egeqHBq6ixhmGO6MRV99XB8nbSfrmESdp/V2p+lbTX1W9cRNSjLsivkLhc3sNfpk5fgihMVhzjCM+BW1h9Cxvnd2UOcqyUQi8p39zgdSmv3f7AdNzkqRHAQYA/rcUoVu9FK3ZHx2puwoyUQAXA6oS2lTkOlaiW0svho2pBdfz/fVfCF6fJEGbjQejStnYREsGH3NunAAgSaZHhzI79xmuvABEFf0udIUDT/Sg8n9FfbZD10Pr+XzpjhdmkNK/5EaJFPR+68I31yMufwevYYwK6QTe71Fhc6kpe/0w1cnCw63DK0JCH/SAPBoPHK6tHgb2iv0NORTP6Y7xEgmQx6zqHdZF9E8EEL3goLVZIWbYs4fQokMewAi7idV1lW8JtEvDFpLTKDNq14FClQP8ItDi2U+9k+I3BGy/n9jFjTmpG/dutAntbDSQ7A7ioXhAoD7NdENloSKAsu0ETK1ceuIBnLBU+sVmZ5SW0wKS508FOh/4jxcopumabJEclQaUrbjx8Ko95WQzap3xMIFduVIysE2jWimWRDQnc3gjQYNy6otSXPTlfd+RNdVuy1hZfsez/DF5ZWiVfapd16ISVi2C29xs71fTmjBPteGrX3fISm2jkgt062DwAeLpzMEVlavE7Yvz8NPyCKWWcp3LsRuFiJ4+AzWbWLlqm3OrPSmEof1ZU0hSrGKiDcX+mHIAtIsCvvTPwU+69mk3orDJyZsQFb2WIWqSpWJyxUpeg3+zCTFK2CbYs3NADV4x6JK6sc6XzaNpg7rScV3MjP1osyJ+MqDsuhhTb/FhgnentOHl2nc7b3UMjcYQxv6Ma3Lxg0/m/eqdug+4w/EKNp4bNBVECgzYnIxHzmMcR5Hgx1b/7ilq4kyoqI2T2KFgCDpReN19fKusvpIM2/gct299jj6QiKO/PLVBPh1xmiDIFnhFUXGS5NBrIJt8dVDpXQ/+tLa+djVpW70/H0P0WAt9EXz0M8Bmzmwtya5nbbRLMZAIugvCry1mx5CZ4glbTu8miwt,iv:8mKQsoPuW084v39vwkPdS4SzED0JWax3tmplVooRO2I=,tag:t2LvmlAeO/4L9Ar0VuiQ0Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:0X02/wE3zjV09iil6uPIqO8qDpXHBJ+DpG/L3M3BtCdkkZGbMDSbtrQOE1ukR/7KSRXtFwkGi6lO1fJYPCS9Qw==,iv:ix3qrQ9PZ8XKstzwcinj5ZfIp8stdtCY7R7DuAk21Qg=,tag:qWwzbMIdREdzxWbiW9ev4w==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:vS6N+FDI,iv:to+EJgS5f+aRul8uYusVkQ0x/K95XcFCsergYgEo/bg=,tag:DLUiDu1A8YeRrOx6qquhZQ==,type:str]
    #ENC[AES256_GCM,data:aBk0Du6heHnq39TNHbl4,iv:mkYvGJEb65sij/iUvjZFuTKqYWpWRpbsl3eET2AXtOs=,tag:8Vbdbe7b3gQ45iRDvRZy6A==,type:comment]
    IMMICH_OAUTH_ENTRA_TENANT_ID: ENC[AES256_GCM,data:DicxU9I2ylcaEpReQHbdegZQVzkwQrXcPNHhaNgCzzgCsWHh,iv:UMSX7ouWKCE5h0dbwT0J9Ls1zNSTU5biSZzw1IE33/M=,tag:7ABSFCByBzpzpG1HIOSE4w==,type:str]
    IMMICH_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:6jfHtqn7Jaa1rrxfozHg4wWR7Twsq++8w0u8U4BDJ3yDHTla,iv:HmFrYEiU4EglZ6SmhQRPwaXDFiATtUkG8PV76p0NQPo=,tag:xrk699WSewlTi4xIun4NFw==,type:str]
    IMMICH_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:r95VIrqmpLkmcftNeNRxg9ejJIyqiyoWTFd791c5BQbxxOEvPjNkEw==,iv:4eJCGCTBmbFLuDz+tutgUhlVtczZ33D4hW6YVlJOC0o=,tag:vY8wjC9rtCIyPsGvzAWwjA==,type:str]
    #ENC[AES256_GCM,data:85p1KH0=,iv:8I6W+HzC8G7VZ4jytGCRPgsgYRmr4A+ovDWyCnewiTk=,tag:7tRFIGohfsliKGxBMi726g==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:/HRzw9WL,iv:sEzXkOVtMOrt2k5ZjL8fN4IPmhurexc0kxLgYFf3K9Y=,tag:tW7BpdFaE5FHQuBjPXsydA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:cGG0MFJsAcdKnc6W7TmZVfXyvAmzHi23VxuiGmVEA5SEHdSkR8Q=,iv:/g5EMDucqkjztqqwT7GLlJDnWqJkswLjLkydRHRy6mo=,tag:uQJbaSesV9acP2z21iSl8Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:rJqFTcow,iv:CYjLfKZfMzRwAGfYiw2drvO8YEVum6tdAj9tagigg94=,tag:X9cRUopT0YzYrhUlbrTTvA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:9tczWoxpWyW3Ih4IinkA9LhpmELtZZHJS2vU3H5At8umHHd/Ex02D63LXBbAqGhxoNVtDFP0FDUMx952eHy/FA==,iv:pEF8VFYApp72izR56pw22l6ObcQW5EMYdDWnRTGZ/wc=,tag:9QD7/UKlzkAYSNFGYpCxew==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:sUOVP+yAQWo=,iv:hw6vuVtmCgq6FFE2XfUkq8oyCcWVPxjSvXr07nTw+jY=,tag:LCWt7GgnmAjV3yg+ufPSEQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:a5fUEg4RC6ISp3iTGW4Ixh8vY9hG+TUXfFZ5Xiiu5ZymtLDPrdPTWA==,iv:1r8lbFWSdsNkVn93kY+iC1DMFG0kmDFq50akCqAL/lA=,tag:OPqsEDFjYhDjRTDyt8jUqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182vhhzupcql0c9l272gm3z004x7hnukt7ptugwqwrqnh2slyu9zskphzdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa21rOHliQ1k2VlZmOHBs
            aEl3UHJXK1FWMDhoMVJURzR4OWFZcjZQMDJzCkszb1Q4RkhIQklsYytvUlNMTkwx
            RitaSXIrWExKNnIrWWRxZTkyNldodzAKLS0tIDV4UnBGQkxQTjAzb20vSnR6VTZF
            K3lmeXI1aXNFOVZUa2pDOG1ZTm8zN1kKqKe0u4rdoKMb1dHX2bWVFQHP4q2HJKlV
            EH0wD0yt+RvRKHb2PWaPyf8z6XviOduc0nfjKsWA6KHK9minv6+8LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T12:05:11Z"
    mac: ENC[AES256_GCM,data:mVRQGIR6qDySow4NAO4Xi/ZoEM2OvxYEQb//5UGspydAdxMntkkSeFBWFo82VGU3897e3sMoEYWZmpndGGXL0tD3Ct7WcaH+75bFdK6Mp+yWNeU+uAKN8cdu884rnbtvDbqueM9Z3A+4vWA50vmSNq7jigXI5q0TWqheYsTBpPM=,iv:0R5yf4pcTqoDCCj7rW2J/MCmLmYpVkJi+vI4LEH34oU=,tag:7Dft6McpytfmghT3908l1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
