#ENC[AES256_GCM,data:rU84YfGpnQQ=,iv:JVSotPsI9UBOMgQHZqSfFrLBOd1JRz6QlQQRsGnOfUU=,tag:qCOWSFu8GyYgwrwGNmldVw==,type:comment]
generic__database_encryption_passphrase: ENC[AES256_GCM,data:NH1ljslfYvOq6Ja0FrUAqXC8UkoWoRfJSKAH0Z8zem6WmxT/sDtfC3zfEXC0ukPLJRPPDqnAZmNFgSEfD9+HWg==,iv:O2z5As4PRMxnedpEU+Bskwge1/MkKBVAQg7vkiBNHgE=,tag:0+jkCnOtavdKOfnad45fvw==,type:str]
generic__database_backup_storage_account_name: ENC[AES256_GCM,data:AhKH2OgRxOmmKa4CfQD+cKRctQ==,iv:feikeHN5gKc/7tO1Tg/Lp8JKqQyUtwPMjn78+7JWsYU=,tag:mwTfzf5UaO5MNdGMPDK63A==,type:str]
generic__database_backup_storage_account_key: ENC[AES256_GCM,data:HdGjxDyJpEdZfobq5GatRXZ2GTFZpp3LVaIBMXnRwzNHH6+s+buPn7TAHC3ZObacXOrkVQkC9VuInxjaoaE+OQfHadpuGMAEjxangeN8vZ2nPl4GBCYd5w==,iv:Awl85Ft7JOME1gQl5eiOPCNYzIbay64fcmBp3p9MemU=,tag:jW1BzdYaq0WiOH9yhJq1uA==,type:str]
#ENC[AES256_GCM,data:bvF/JgA=,iv:6ohFEwjJlQz9gG8+WubBFTVdvlGrdfUkOrAIBsITIqQ=,tag:Z8ZseSFvJfr6NDNrdbbw9w==,type:comment]
#ENC[AES256_GCM,data:tM3tWIQ0IuvCGItPjHPUuaz1sBwPJg==,iv:NEDG/rNiJCr9d1Rpxl72wszExb8fXfA1/HEbnjBDprM=,tag:x3TBxhEWVYHgDNIx7s/abA==,type:comment]
apps__traefik_forward_auth_secret: ENC[AES256_GCM,data:4b8Kp0BN81P9ZRavFau4GnA4kHCIwGVrj4fqpA0h3567lI/VUdFsjjer5fCvZPT3HtN7FRNxyI5b9n7AbljKLQ==,iv:oKyaO4JOoA/hTROcG2wp3JMRHUs9QVRzm6KGBZp0U6E=,tag:hx22pBmNJPC4L0NkQGTkiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182vhhzupcql0c9l272gm3z004x7hnukt7ptugwqwrqnh2slyu9zskphzdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT1RYWUFvZE9UQkcwb1Nx
            M2U4WUxwdi9JVVJlUzZFWWlkOXY5ejM0MUhNClJ0NUhQYjlWb3VIYmgra0dUWnhW
            ZU5JdVdYSzBXSExmbjN6cEZJMUtOYUkKLS0tIDdGTi9md1F2WHRtMVpXMUhSK2hI
            eVBKRXVRTE0xSGdTQzF6enJtNnMzOGcKfIhR/2B8E7FhoP5b+fRdpPwIwE7gOrIa
            mR6EnBhQi6Cr/LM/7nwWvCt/E/2IoDLMPPl7f1xyDPIjV/fY5XncqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T14:17:42Z"
    mac: ENC[AES256_GCM,data:NVurGp2LhVio/GiZsC4JpqCBqIVYyAdpcNT6a2JFEEqiIS4cptI00kXqgvuyYFd9NWPxdQZyN7xqrkjblSuWJQcYgUCsabtHfofcjnH238Awqo3Q7j1Kr3JQOeR/tMDnoYO8MMDX2mP4qLylmvzUi3+8Kx7yVosTQ0EwoGeCooI=,iv:I1fhgqD31EXufsieZs7NzuNwCjMjrMc7QOjzJKtLpZE=,tag:LDPueuAr/X6sKjdQMV89gQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
