apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
stringData:
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:yZcUBpw7F4MVBJIEpYjISIoXfUc5d6YisjMbV8eipFY=,iv:zAnZaL2x3535ramIxzbMcu4udBXnvvxkTz1j1T/xEpQ=,tag:T7/G6P3T3typP5mDbS/yJg==,type:str]
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:1X1GgEXLaCX4muWqt//RuZN4vil0eliYm8ZYR8CuUfGqkpkL,iv:HrJgzi9q3Fh+s2cTZNxfyf8wqwIGUd6agFBcMqHU1fk=,tag:28SDJEXF+OaDWHDgok0hJg==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:Ddl7Xm+cutDVL72agiLIOtSrnV9aaEL2yAnrz22YcjYfcX8039NRpQ==,iv:Vl/nf6BaLXyK78Asjrx87wwjupSK12SbXY+uPbR518Y=,tag:4hTxMa+ZM4H5KVBNfwk1MA==,type:str]
    OAUTH2_PROXY_OIDC_ISSUER_URL: ENC[AES256_GCM,data:LTAKIswoF7v7FILAQsHfjoSE39he6c7uA+nULpf/b1Q1mX3SGhgfEgknz9DchcZmeHhYlxHwiKVoBVDizkSiwo4KnSwGer65M98L,iv:o91kFawKDeEMRXQ5vaJ3YbL7/pYMCBCjHmUcn7HnNZA=,tag:CUnrD3VOnCc/x27To816FQ==,type:str]
    OAUTH2_PROXY_AZURE_TENANT: ENC[AES256_GCM,data:XVAvQjM5L1lUqZ/aW+GWGyqzCDLZKi8jrGab9ID8aMGlpx8V,iv:CmaZ7f5EOnTQko3oxs9sbfJ5TmVyoSaS8/mgNB//TII=,tag:CbCAxylXq4LeyS66xNzg9g==,type:str]
    OAUTH2_PROXY_COOKIE_DOMAINS: ENC[AES256_GCM,data:s7pWR//fsgJtcAf6zPk=,iv:xD7Oca1XVLuJj9BiEAyuHfbkE4Dq+gUks/aVd+TCzYo=,tag:hcoavIR4Dh6L5QMXtKckmg==,type:str]
    OAUTH2_PROXY_EMAIL_DOMAINS: ENC[AES256_GCM,data:FT5E0COYCKKrTRpYtM0=,iv:LK1iya1F03Rmyou5CFyRZIgN2pSLaNQpnj9+eqm2DDE=,tag:nQhcSVDPnKUyucy4d+UCbA==,type:str]
    OAUTH2_PROXY_WHITELIST_DOMAINS: ENC[AES256_GCM,data:AZg39S5pHeBeBLBVdwWz,iv:xpxX/a1UtrbMaavSZVZr3Mb8BKrRPrt7R3EGZrZ1e0U=,tag:CouozY9QwGBPvFXx1M5low==,type:str]
    OAUTH2_PROXY_REDIS_PASSWORD: ENC[AES256_GCM,data:2nKDCHc1Cu2vY4kEE2vGMg/xzW8b8fWMYhmVat22uVdTaev6i1tRiw==,iv:HyCnnv5Uue94dSNLHEKacBYxkoTLsxnicY3aIqR+eJY=,tag:2c4aIczf7Ui4dT0Ve461zA==,type:str]
    OAUTH2_PROXY_REDIS_SENTINEL_MASTER_NAME: ENC[AES256_GCM,data:wpifz0ndvZvX/cyI,iv:1CBZ/DkRFxnT91Ii+q405mhuvgD5bxqV1EfO3eWv7jY=,tag:at1q5+BqsTKAb5oob+XP9Q==,type:str]
    OAUTH2_PROXY_REDIS_SENTINEL_PASSWORD: ENC[AES256_GCM,data:wfVZlap75pvTsmJOh3pgKwXcN8DRCKHkqe7abH9NsFTOGTxn5d8wMA==,iv:ml4Xuh06ZJ3Ff4zEPNU/Glh93YFafq7k57SkNhW5EwA=,tag:QCAKHYgff6vhZFK/ifPmkQ==,type:str]
    OAUTH2_PROXY_REDIS_SENTINEL_CONNECTION_URLS: ENC[AES256_GCM,data:r9r4FxeYzMz/7z8yqhA69FPWdXJEgP2M98bDPOLuDLRDJ3icKd7uQ6iZh0J3DQiLcTzC2bLALlrQlD/SsNo0jpGkHps=,iv:6HKw9yhePvONO7x8A7kcnhWhnlTbBOO965V8ljUBCGw=,tag:tzorYQahMbD8BGgEnldGMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182vhhzupcql0c9l272gm3z004x7hnukt7ptugwqwrqnh2slyu9zskphzdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa21rOHliQ1k2VlZmOHBs
            aEl3UHJXK1FWMDhoMVJURzR4OWFZcjZQMDJzCkszb1Q4RkhIQklsYytvUlNMTkwx
            RitaSXIrWExKNnIrWWRxZTkyNldodzAKLS0tIDV4UnBGQkxQTjAzb20vSnR6VTZF
            K3lmeXI1aXNFOVZUa2pDOG1ZTm8zN1kKqKe0u4rdoKMb1dHX2bWVFQHP4q2HJKlV
            EH0wD0yt+RvRKHb2PWaPyf8z6XviOduc0nfjKsWA6KHK9minv6+8LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T22:13:51Z"
    mac: ENC[AES256_GCM,data:LC3rFFVmZkNOQf5uoOVpjeHBbLVTkRMUHwFcuHMrr18vZpgy4YO63M4f7Afc99xcrsn1sBcpqqhBhmYNSSHdr81bWF/9ThB2X/AdzomZWbmWFmQHd1Hg7JbAhtgf6IpZtHb97pe2FUVPAGmHNRJ0HpXBStPkxyo2fC4M+n0CU5k=,iv:WHGdeIqao3c0HID1dgtxXmn/Too5F8aUFN9pNkqzGTw=,tag:gCeFZf+Mri3iN4sUvHaWOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
