services:
  phpmyadmin:
    image: phpmyadmin:5.2.3-apache@sha256:3feff4c3b4c73143add178ce318c7c090a98503c1bc895341a2677a3780560a1
    container_name: phpmyadmin
    depends_on:
      - traefik
    networks:
      - phpmyadmin-frontend
    restart: always
    security_opt:
      - no-new-privileges=true
    mem_limit: 1024m
    environment:
      - TZ=${TZ}
      #- PMA_ARBITRARY=1 # Allows you to select a DB server on login screen
      - HIDE_PHP_VERSION=true
    labels:
      # Homepage
      - homepage.group=Infrastructure
      - homepage.name=phpMyAdmin
      - homepage.icon=phpmyadmin.svg
      - homepage.href=https://phpmyadmin.$DOMAINNAME
      - homepage.description=Database Management
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=phpmyadmin-frontend"
      ## Middlewares
      - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-auth@file"
      ## HTTP Services
      - "traefik.http.routers.phpmyadmin-rtr.service=phpmyadmin-svc"
      - "traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80"
      ## Router for Gatus â€” bypass auth if secret header is present
      - "traefik.http.routers.phpmyadmin-monitor-rtr.rule=Host(`phpmyadmin.$DOMAINNAME`) && Header(`X-Monitor-Key`, `$GENERIC_MONITORING_HEADER_SECRET`)"
      - "traefik.http.routers.phpmyadmin-monitor-rtr.service=phpmyadmin-svc"
      - "traefik.http.routers.phpmyadmin-monitor-rtr.priority=100"  # Higher priority so it matches first

networks:
  phpmyadmin-frontend:
    name: phpmyadmin-frontend
